🔧 chore(RDSDiskSpaceLimit.md): add missing 'bash' syntax highlighting to code block
Fixes linting error in markdownlint

```
Error: content/runbooks/rds/RDSDiskSpaceLimit.md:80 MD031/blanks-around-fences Fenced code blocks should be surrounded by blank lines [Context: "```"] https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md031.md
Error: content/runbooks/rds/RDSDiskSpaceLimit.md:83 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"] https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md040.md

```